# Generated by Django 4.2.3 on 2023-07-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='words',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='words',
            field=models.ManyToManyField(to='parserAPP.keywords'),
        ),
    ]
