# Generated by Django 4.2.3 on 2023-08-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPP', '0003_regions_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regions',
            name='image',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='regions'),
        ),
    ]
