# Generated by Django 4.2.3 on 2023-08-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPP', '0004_remove_regions_image_vacancies_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
