# Generated by Django 4.2.3 on 2023-08-05 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPP', '0009_alter_regions_region_alter_vacancies_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='regions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parserAPP.regions'),
        ),
    ]
