# Generated by Django 4.2.3 on 2023-08-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPP', '0012_alter_vacancies_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='regions',
            field=models.CharField(max_length=30),
        ),
    ]
